version: '3.7'

services:
  server:
    build: .
    command: poetry run python gui.py
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app/
    ports:
      - ${PORT}:${PORT}
    container_name: underground-chat-cli